#!/bin/sh
#SBATCH -t 23:00:00
#SBATCH --job-name=Gillette
#SBATCH --error=er_cuda.txt
#SBATCH --output=cuda.txt
#SBATCH -p gpu
##SBATCH --ntasks 1
#SBATCH --gres=gpu:1

##mpirun --mca btl ^openib ./ef.out test_cuda.conf

##mpirun -np 1 --mca btl ^openib ./ef.out test_cuda.conf

 srun ./ef.out test_cuda.conf
